repos:
- repo: local
  hooks:
  - id: scan-secrets
    name: Scan Secrets
    entry: ./scripts/githooks/scan-secrets.sh
    args: ["check=staged-changes"]
    language: script
    pass_filenames: false
- repo: local
  hooks:
  - id: check-file-format
    name: Check File Format
    entry: ./scripts/githooks/check-file-format.sh
    args: ["check=staged-changes"]
    language: script
    pass_filenames: false
- repo: local
  hooks:
  - id: check-markdown-format
    name: Check Markdown Format
    entry: ./scripts/githooks/check-markdown-format.sh
    args: ["check=staged-changes"]
    language: script
    pass_filenames: false
- repo: local
  hooks:
  - id: check-terraform-format
    name: Check Terraform Format
    entry: ./scripts/githooks/check-terraform-format.sh
    language: script
    pass_filenames: false
