name: "Acceptance Stage"

on:
  workflow_call:
    inputs:
      build_datetime:
        description: "Build datetime, set by the CI/CD pipeline workflow"
        required: true
        type: string
      build_timestamp:
        description: "Build timestamp, set by the CI/CD pipeline workflow"
        required: true
        type: string
      build_epoch:
        description: "Build epoch, set by the CI/CD pipeline workflow"
        required: true
        type: string
      nodejs_version:
        description: "Node.js version, set by the CI/CD pipeline workflow"
        required: true
        type: string
      python_version:
        description: "Python version, set by the CI/CD pipeline workflow"
        required: true
        type: string
      terraform_version:
        description: "Terraform version, set by the CI/CD pipeline workflow"
        required: true
        type: string
      version:
        description: "Version of the software, set by the CI/CD pipeline workflow"
        required: true
        type: string

jobs:
  environment-set-up:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - name: "Create infractructure"
        run: |
          echo "Creating infractructure ..."
      - name: "Update database"
        run: |
          echo "Updating database ..."
      - name: "Deploy application"
        run: |
          echo "Deploying application ..."
  accessibility-test:
    runs-on: ubuntu-latest
    needs: environment-set-up
    timeout-minutes: 10
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - name: "Run accessibility test"
        run: |
          echo "Running accessibility test ..."
      - name: "Save result"
        run: |
          echo "Saveing result ..."
  load-test:
    runs-on: ubuntu-latest
    needs: environment-set-up
    timeout-minutes: 10
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - name: "Run load test"
        run: |
          echo "Running load test ..."
      - name: "Save result"
        run: |
          echo "Saveing result ..."
  security-test:
    runs-on: ubuntu-latest
    needs: environment-set-up
    timeout-minutes: 10
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - name: "Run security test"
        run: |
          echo "Running security test ..."
      - name: "Save result"
        run: |
          echo "Saveing result ..."
  environment-tear-down:
    runs-on: ubuntu-latest
    needs: [accessibility-test, load-test, security-test]
    if: always()
    timeout-minutes: 5
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - name: "Tear down environment"
        run: |
          echo "Tearing down environment ..."
